
import java.util.Random;
import javax.swing.*;
import java.awt.*;
public class AddRandom extends javax.swing.JFrame {
     // Creates new form AddRandom
    public AddRandom() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(this);
        
        
        
        Random rand = new Random();
        String[] teams = {"", "الأهلى", "الزمالك", "وادى دجلة", "الإسماعيلى", "بتروجت"};

        int hour = rand.nextInt(24);
        int counter1 = 1 + rand.nextInt(5);
        int counter2 = 1 + rand.nextInt(5);
        while (true) {
            if (counter1 != counter2) {
                break;
            }
            counter1 = rand.nextInt(5);
            counter2 = rand.nextInt(5);
        }
        String T1;
        String T2;
        T1 = teams[counter1];
        T2 = teams[counter2];
        Send(hour, T1, T2);
        
        ShownText.setText("The Hour was already in the Data Base :) so that's What We Have");
        ShownText.setText("If You Wish To add a Match you know , Let us Know ");
        JButton Submit=new JButton("Submit");
        JTextField FirstTeam=new JTextField("الفريق الأول");
        JTextField SecondTeam=new JTextField("الفريق الثانى");
        this.add(Submit);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Team11 = new javax.swing.JLabel();
        Team12 = new javax.swing.JLabel();
        Time1 = new javax.swing.JLabel();
        ShownText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Team11.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team11.setForeground(new java.awt.Color(204, 204, 204));
        Team11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team11.setText("االزمالك");
        Team11.setToolTipText("الفريق");

        Team12.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team12.setForeground(new java.awt.Color(204, 204, 204));
        Team12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team12.setText("الأهلى");
        Team12.setToolTipText("الفريق");

        Time1.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        Time1.setForeground(new java.awt.Color(255, 0, 0));
        Time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Team12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Time1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 370, 63);

        ShownText.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        ShownText.setForeground(new java.awt.Color(0, 136, 110));
        ShownText.setText("esgdrfhgnvjk,ljszdxgfhghjb ");
        getContentPane().add(ShownText);
        ShownText.setBounds(60, 90, 320, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 390, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void  Send(int h, String S, String T) {
                //nb3aT Lel DataBase
            }

            public String Recieve1st() {
                String s = "";
                return s;
            }

            public String Recieve2nd() {
                String s = "";
                return s;
            }

            public int RecieveHour() {
                int h = 0;
                return h;
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ShownText;
    private javax.swing.JLabel Team11;
    private javax.swing.JLabel Team12;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
