
import java.awt.*;
import java.text.AttributedCharacterIterator;
import java.util.*;
import javax.swing.*;


public class GUIMe extends JFrame {

    //ImageIcon Image;

    // Creates new form GUIMe
    
    public GUIMe() {

        
        initComponents();
        setLocationRelativeTo(this);
        setSize(457,600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        String Team1 = JOptionPane.showInputDialog("Input first Team");
        String Team2 = JOptionPane.showInputDialog("input Second Team");
        Team11.setText(Team1);
        Team12.setText(Team1);
        Team13.setText(Team1);
        Team21.setText(Team2);
        Team22.setText(Team2);
        Team23.setText(Team2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Time1 = new javax.swing.JLabel();
        Team11 = new javax.swing.JLabel();
        Team21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Time2 = new javax.swing.JLabel();
        Team12 = new javax.swing.JLabel();
        Team22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Team13 = new javax.swing.JLabel();
        Team23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Team17 = new javax.swing.JLabel();
        Team27 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Team15 = new javax.swing.JLabel();
        Team25 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Team16 = new javax.swing.JLabel();
        Team26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 46, 181));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 146, 255));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Aldhabi", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("الدورى المصرى");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(121, 11, 142, 56);

        jLabel1.setBackground(new java.awt.Color(255, 102, 204));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("HOME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 70, 52, 24);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("AWAY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 52, 24);

        jPanel5.setBackground(new java.awt.Color(255, 171, 50));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel5.setFocusable(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(470, 60));

        Time1.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        Time1.setForeground(new java.awt.Color(192, 43, 34));
        Time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time1.setText("00:00");

        Team11.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team11.setText("الأهلى");
        Team11.setToolTipText("الفريق");

        Team21.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team21.setText("الزمالك");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Time1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Team11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(Team21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Team11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Time1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 100, 440, 60);

        jPanel7.setBackground(new java.awt.Color(255, 171, 50));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel7.setFocusable(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(470, 60));

        Time2.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        Time2.setForeground(new java.awt.Color(192, 43, 34));
        Time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time2.setText("00:00");

        Team12.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team12.setText("الأهلى");
        Team12.setToolTipText("الفريق");

        Team22.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team22.setText("الزمالك");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Time2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(Team12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(Team22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Team12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Time2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 170, 440, 60);

        jPanel1.setBackground(new java.awt.Color(255, 171, 50));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 60));

        Team13.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team13.setText("الأهلى");
        Team13.setToolTipText("الفريق");

        Team23.setBackground(new java.awt.Color(220, 207, 171));
        Team23.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team23.setText("الزمالك");

        jLabel3.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 43, 34));
        jLabel3.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Team13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 240, 440, 60);

        jPanel6.setBackground(new java.awt.Color(255, 171, 50));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel6.setPreferredSize(new java.awt.Dimension(380, 60));

        Team17.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team17.setText("الأهلى");
        Team17.setToolTipText("الفريق");

        Team27.setBackground(new java.awt.Color(220, 207, 171));
        Team27.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team27.setText("الزمالك");

        jLabel8.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(192, 43, 34));
        jLabel8.setText("00:00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team27, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Team17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 310, 440, 60);

        jPanel2.setBackground(new java.awt.Color(255, 171, 50));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(380, 60));

        Team15.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team15.setText("الأهلى");
        Team15.setToolTipText("الفريق");

        Team25.setBackground(new java.awt.Color(220, 207, 171));
        Team25.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team25.setText("الزمالك");

        jLabel5.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(192, 43, 34));
        jLabel5.setText("00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Team15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 380, 440, 60);

        jPanel3.setBackground(new java.awt.Color(255, 171, 50));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 60));

        Team16.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team16.setText("الأهلى");
        Team16.setToolTipText("الفريق");

        Team26.setBackground(new java.awt.Color(220, 207, 171));
        Team26.setFont(new java.awt.Font("Aldhabi", 0, 40)); // NOI18N
        Team26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Team26.setText("الزمالك");

        jLabel6.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(192, 43, 34));
        jLabel6.setText("00:00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Team16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 450, 440, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/11.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 440, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Team11;
    private javax.swing.JLabel Team12;
    private javax.swing.JLabel Team13;
    private javax.swing.JLabel Team15;
    private javax.swing.JLabel Team16;
    private javax.swing.JLabel Team17;
    private javax.swing.JLabel Team21;
    private javax.swing.JLabel Team22;
    private javax.swing.JLabel Team23;
    private javax.swing.JLabel Team25;
    private javax.swing.JLabel Team26;
    private javax.swing.JLabel Team27;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel Time2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
